linters:
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 2

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes
